//Limits of Liability - Under no circumstances shall Performance Motion Devices, Inc. or its affiliates, partners, or suppliers be liable for any indirect
// incidental, consequential, special or exemplary damages arising out or in connection with the use this example,
// whether or not the damages were foreseeable and whether or not Performance Motion Devices, Inc. was advised of the possibility of such damages.
// Determining the suitability of this example is the responsibility of the user and subsequent usage is at their sole risk and discretion.
// There are no licensing restrictions associated with this example.

//  This contain the main() function for the PIC32 example

//#define PMD_CAN_INTERFACE
#define PMD_SPI_INTERFACE
//#define PMD_W32SERIAL_INTERFACE

#include "C-Motion.h"
#include "PMDutil.h"
#include "PMDdiag.h"
#include "PMDsys.h"
#include "Examples.h"
#include <stdio.h>


int main()

{
 
    PMDuint16 generation, motorType, numberAxes, chip_count, custom, major, minor;
	PMDAxisHandle hAxis1; 
	PMDresult result;

    InitDBPrintf();
    
    // see ControlLED4 in PMDsys.c
    InitLED4();
    
	PMDSetupAxisInterface_SPI(&hAxis1, PMDAxis1, 0);
    if(result)
	{
		printf("Error:Could not open serial port code=%x\n",result);
		return;
	}	
	
	result=PMDGetVersion( &hAxis1, &generation, &motorType, &numberAxes, &chip_count, &custom, &major, &minor );
    if(result)
	{
		printf("result=%x\n",result);
		return;
	}
	else
	{	
	printf("PMD Motion Processor MC%d%d%d%d0 v%d.%d\n\n", generation, motorType, numberAxes, chip_count, major, minor);

	}
	
	// To Do:
	// Add any initialization commands like SetupAxis1() generated by Pro-Motion.
	// Then start a move by call ProfileMove() 

   	return;

}



     