#ifndef PMD_OPCodes
#define PMD_OPCodes

//  Magellan command code declarations
//
//  Performance Motion Devices, Inc.
//

#if defined(__cplusplus)
extern "C" {
#endif

enum {

    PMDOPNoOperation               = 0x00,
    PMDOPGetProductInfo            = 0x01,
    PMDOPSetMotorType              = 0x02,
    PMDOPGetMotorType              = 0x03,
    PMDOPSetBiQuadCoefficient      = 0x04,
    PMDOPGetBiQuadCoefficient      = 0x05,
    PMDOPSetMotorLimit             = 0x06,
    PMDOPGetMotorLimit             = 0x07,
    PMDOPSetAuxiliaryEncoderSource = 0x08,
    PMDOPGetAuxiliaryEncoderSource = 0x09,
    PMDOPSetSPIMode                = 0x0A,
    PMDOPGetSPIMode                = 0x0B,
    PMDOPSetPWMFrequency           = 0x0C,
    PMDOPGetPWMFrequency           = 0x0D,
    PMDOPGetDriveStatus            = 0x0E,
    PMDOPSetMotorBias              = 0x0F,

    PMDOPSetPosition               = 0x10,
    PMDOPSetVelocity               = 0x11,
    PMDOPSetCANMode                = 0x12,
    PMDOPSetJerk                   = 0x13,
    PMDOPSetGearRatio              = 0x14,
    PMDOPGetCANMode                = 0x15,
    PMDOPSetProfileParameter       = 0x16,
    PMDOPGetProfileParameter       = 0x17,


    PMDOPUpdate                    = 0x1A,
    PMDOPSetOvertemperatureLimit   = 0x1B,
    PMDOPGetOvertemperatureLimit   = 0x1C,
    PMDOPGetCommandedPosition      = 0x1D,
    PMDOPGetCommandedVelocity      = 0x1E,



    PMDOPSetFeedbackParameter      = 0x21,
    PMDOPGetFeedbackParameter      = 0x22,
    PMDOPSetDrivePWM               = 0x23,
    PMDOPGetDrivePWM               = 0x24,
    PMDOPSetKp                     = 0x25,
    PMDOPSetKi                     = 0x26,
    PMDOPSetKd                     = 0x27,
    PMDOPGetTraceValue             = 0x28,
    PMDOPSetAnalogCalibration      = 0x29,
    PMDOPGetAnalogCalibration      = 0x2A,
    PMDOPSetKvff                   = 0x2B,
    PMDOPGetPhaseAngle             = 0x2C,
    PMDOPGetMotorBias              = 0x2D,
    PMDOPRestoreOperatingMode      = 0x2E,
    PMDOPSetInterruptMask          = 0x2F,

    PMDOPDriveNVRAM                = 0x30,
    PMDOPGetEventStatus            = 0x31,
    PMDOPSetBreakpointUpdateMask   = 0x32,
    PMDOPGetBreakpointUpdateMask   = 0x33,
    PMDOPResetEventStatus          = 0x34,
    PMDOPExecutionControl          = 0x35,
    PMDOPGetCaptureValue           = 0x36,
    PMDOPGetActualPosition         = 0x37,
    PMDOPGetVelocityLoopValue      = 0x38,
    PMDOPReset                     = 0x39,
    PMDOPGetActiveMotorCommand     = 0x3A,
    PMDOPSetSampleTime             = 0x3B,
    PMDOPGetSampleTime             = 0x3C,
    PMDOPGetRuntimeError           = 0x3D,
    PMDOPGetTime                   = 0x3E,


    PMDOPGetBusVoltage             = 0x40,
    PMDOPSetCurrentFoldback        = 0x41,
    PMDOPGetCurrentFoldback        = 0x42,
    PMDOPSetCurrentControlMode     = 0x43,
    PMDOPGetCurrentControlMode     = 0x44,
    PMDOPSetAxisOutMask            = 0x45,
    PMDOPGetAxisOutMask            = 0x46,
    PMDOPClearPositionError        = 0x47,
    PMDOPSetEventAction            = 0x48,
    PMDOPGetEventAction            = 0x49,
    PMDOPGetPosition               = 0x4A,
    PMDOPGetVelocity               = 0x4B,
    PMDOPGetAcceleration           = 0x4C,
    PMDOPSetActualPosition         = 0x4D,



    PMDOPGetKp                     = 0x50,
    PMDOPGetKi                     = 0x51,
    PMDOPGetKd                     = 0x52,
    PMDOPGetTemperature            = 0x53,
    PMDOPGetKvff                   = 0x54,
    PMDOPGetPositionLoopValue      = 0x55,
    PMDOPGetInterruptMask          = 0x56,
    PMDOPGetActiveOperatingMode    = 0x57,
    PMDOPGetJerk                   = 0x58,
    PMDOPGetGearRatio              = 0x59,
    PMDOPGetFOCValue               = 0x5A,
    PMDOPMultiUpdate               = 0x5B,


    PMDOPSetCurrent                = 0x5E,
    PMDOPGetCurrent                = 0x5F,

    PMDOPGetDriveFaultParameter    = 0x60,

    PMDOPSetDriveFaultParameter    = 0x62,
    PMDOPSetCommutationParameter   = 0x63,
    PMDOPGetCommutationParameter   = 0x64,
    PMDOPSetOperatingMode          = 0x65,
    PMDOPGetOperatingMode          = 0x66,
    PMDOPSetPositionLoop           = 0x67,
    PMDOPGetPositionLoop           = 0x68,
    PMDOPGetMotorCommand           = 0x69,
    PMDOPSetStartVelocity          = 0x6A,
    PMDOPGetStartVelocity          = 0x6B,
    PMDOPClearDriveFaultStatus     = 0x6C,
    PMDOPGetDriveFaultStatus       = 0x6D,
    PMDOPGetOutputMode             = 0x6E,
    PMDOPCalibrateAnalog           = 0x6F,

    PMDOPGetDriveValue             = 0x70,
    PMDOPGetCurrentLoopValue       = 0x71,
    PMDOPSetPhaseInitializeTime    = 0x72,
    PMDOPSetCurrentLoop            = 0x73,
    PMDOPGetCurrentLoop            = 0x74,
    PMDOPSetPhaseCounts            = 0x75,
    PMDOPSetPhaseOffset            = 0x76,
    PMDOPSetMotorCommand           = 0x77,
    PMDOPSetVelocityLoop           = 0x78,
    PMDOPGetVelocityLoop           = 0x79,
    PMDOPInitializePhase           = 0x7A,
    PMDOPGetPhaseOffset            = 0x7B,
    PMDOPGetPhaseInitializeTime    = 0x7C,
    PMDOPGetPhaseCounts            = 0x7D,
    PMDOPSetDriveCommandMode       = 0x7E,
    PMDOPGetDriveCommandMode       = 0x7F,

    PMDOPSetLimitSwitchMode        = 0x80,
    PMDOPGetLimitSwitchMode        = 0x81,
    PMDOPWriteIO                   = 0x82,
    PMDOPReadIO                    = 0x83,
    PMDOPSetPhaseAngle             = 0x84,
    PMDOPSetPhaseParameter         = 0x85,
    PMDOPGetPhaseParameter         = 0x86,
    PMDOPSetAxisMode               = 0x87,
    PMDOPGetAxisMode               = 0x88,
    PMDOPSetDefault                = 0x89,
    PMDOPGetDefault                = 0x8A,
    PMDOPSetSerialPortMode         = 0x8B,
    PMDOPGetSerialPortMode         = 0x8C,
    PMDOPSetEncoderModulus         = 0x8D,
    PMDOPGetEncoderModulus         = 0x8E,
    PMDOPGetVersion                = 0x8F,

    PMDOPSetAcceleration           = 0x90,
    PMDOPSetDeceleration           = 0x91,
    PMDOPGetDeceleration           = 0x92,
    PMDOPSetKaff                   = 0x93,
    PMDOPGetKaff                   = 0x94,
    PMDOPSetIntegrationLimit       = 0x95,
    PMDOPGetIntegrationLimit       = 0x96,
    PMDOPSetPositionErrorLimit     = 0x97,
    PMDOPGetPositionErrorLimit     = 0x98,
    PMDOPGetPositionError          = 0x99,
    PMDOPGetIntegral               = 0x9A,
    PMDOPGetDerivative             = 0x9B,
    PMDOPSetDerivativeTime         = 0x9C,
    PMDOPGetDerivativeTime         = 0x9D,
    PMDOPSetKout                   = 0x9E,
    PMDOPGetKout                   = 0x9F,

    PMDOPSetProfileMode            = 0xA0,
    PMDOPGetProfileMode            = 0xA1,
    PMDOPSetSignalSense            = 0xA2,
    PMDOPGetSignalSense            = 0xA3,
    PMDOPGetSignalStatus           = 0xA4,
    PMDOPGetInstructionError       = 0xA5,
    PMDOPGetActivityStatus         = 0xA6,
    PMDOPGetCommandedAcceleration  = 0xA7,
    PMDOPSetTrackingWindow         = 0xA8,
    PMDOPGetTrackingWindow         = 0xA9,
    PMDOPSetSettleTime             = 0xAA,
    PMDOPGetSettleTime             = 0xAB,
    PMDOPClearInterrupt            = 0xAC,
    PMDOPGetActualVelocity         = 0xAD,
    PMDOPSetGearMaster             = 0xAE,
    PMDOPGetGearMaster             = 0xAF,

    PMDOPSetTraceMode              = 0xB0,
    PMDOPGetTraceMode              = 0xB1,
    PMDOPSetTraceStart             = 0xB2,
    PMDOPGetTraceStart             = 0xB3,
    PMDOPSetTraceStop              = 0xB4,
    PMDOPGetTraceStop              = 0xB5,
    PMDOPSetTraceVariable          = 0xB6,
    PMDOPGetTraceVariable          = 0xB7,
    PMDOPSetTracePeriod            = 0xB8,
    PMDOPGetTracePeriod            = 0xB9,
    PMDOPGetTraceStatus            = 0xBA,
    PMDOPGetTraceCount             = 0xBB,
    PMDOPSetSettleWindow           = 0xBC,
    PMDOPGetSettleWindow           = 0xBD,
    PMDOPSetActualPositionUnits    = 0xBE,
    PMDOPGetActualPositionUnits    = 0xBF,

    PMDOPSetBufferStart            = 0xC0,
    PMDOPGetBufferStart            = 0xC1,
    PMDOPSetBufferLength           = 0xC2,
    PMDOPGetBufferLength           = 0xC3,
    PMDOPSetBufferWriteIndex       = 0xC4,
    PMDOPGetBufferWriteIndex       = 0xC5,
    PMDOPSetBufferReadIndex        = 0xC6,
    PMDOPGetBufferReadIndex        = 0xC7,
    PMDOPWriteBuffer               = 0xC8,
    PMDOPReadBuffer                = 0xC9,
    PMDOPSetBufferFunction         = 0xCA,
    PMDOPGetBufferFunction         = 0xCB,

    PMDOPReadBuffer16              = 0xCD,
    PMDOPGetStepRange              = 0xCE,
    PMDOPSetStepRange              = 0xCF,

    PMDOPSetStopMode               = 0xD0,
    PMDOPGetStopMode               = 0xD1,
    PMDOPSetAutoStopMode           = 0xD2,
    PMDOPGetAutoStopMode           = 0xD3,
    PMDOPSetBreakpoint             = 0xD4,
    PMDOPGetBreakpoint             = 0xD5,
    PMDOPSetBreakpointValue        = 0xD6,
    PMDOPGetBreakpointValue        = 0xD7,
    PMDOPSetCaptureSource          = 0xD8,
    PMDOPGetCaptureSource          = 0xD9,
    PMDOPSetEncoderSource          = 0xDA,
    PMDOPGetEncoderSource          = 0xDB,
    PMDOPSetMotorMode              = 0xDC,
    PMDOPGetMotorMode              = 0xDD,
    PMDOPSetEncoderToStepRatio     = 0xDE,
    PMDOPGetEncoderToStepRatio     = 0xDF,

    PMDOPSetOutputMode             = 0xE0,
    PMDOPGetInterruptAxis          = 0xE1,
    PMDOPSetCommutationMode        = 0xE2,
    PMDOPGetCommutationMode        = 0xE3,
    PMDOPSetPhaseInitializeMode    = 0xE4,
    PMDOPGetPhaseInitializeMode    = 0xE5,
    PMDOPSetPhasePrescale          = 0xE6,
    PMDOPGetPhasePrescale          = 0xE7,
    PMDOPSetPhaseCorrectionMode    = 0xE8,
    PMDOPGetPhaseCorrectionMode    = 0xE9,
    PMDOPGetPhaseCommand           = 0xEA,
    PMDOPSetMotionCompleteMode     = 0xEB,
    PMDOPGetMotionCompleteMode     = 0xEC,
    PMDOPSetAxisOutSource          = 0xED,
    PMDOPGetAxisOutSource          = 0xEE,
    PMDOPReadAnalog                = 0xEF,



    PMDOPSetSynchronizationMode    = 0xF2,
    PMDOPGetSynchronizationMode    = 0xF3,

    PMDOPAdjustActualPosition      = 0xF5,
    PMDOPSetFOC                    = 0xF6,
    PMDOPGetFOC                    = 0xF7,
    PMDOPGetChecksum               = 0xF8,
    PMDOPSetUpdateMask             = 0xF9,
    PMDOPGetUpdateMask             = 0xFA,
    PMDOPSetFaultOutMask           = 0xFB,
    PMDOPGetFaultOutMask           = 0xFC,



};

#if defined(__cplusplus)
}
#endif

#endif


